- .dockerignore
- .github/workflows/docker-publish.yml
- .github/workflows/tmkms.yml
- Dockerfile.nitro
- NOTICE
> Problem: (fix #23)missing workflow to build and publish tmkms-nitro-enclave

- providers/nitro/nitro-helper/src/command.rs
- providers/nitro/nitro-helper/src/main.rs
Solution: provide flag for CID
> Problem: (fix #25)fixed CID for Nitro Enclave

- Cargo.lock
- Cargo.toml
- providers/nitro/nitro-enclave/Cargo.toml
- providers/nitro/nitro-helper/Cargo.toml
- providers/sgx/sgx-app/Cargo.toml
- providers/sgx/sgx-runner/Cargo.toml
- providers/softsign/Cargo.toml
Solution: bumped together all tendermint-rs crates + prost
> Problem: upgrade to tendermint 0.18 fails (fixes #35 #38)

- providers/nitro/nitro-helper/src/command.rs
Solution: fixed the code block according to the suggestion
> Problem: warning in a new clippy version

- providers/sgx/sgx-runner/src/command.rs
> Problem: (fix #56)extra ? operator is accidentally added

- Cargo.lock
- Cargo.toml
- integration-test/integration_test/bot.py
- integration-test/tests/test_integration_test.py
- providers/nitro/nitro-enclave/Cargo.toml
- providers/nitro/nitro-enclave/src/nitro.rs
- providers/nitro/nitro-helper/Cargo.toml
- providers/sgx/sgx-app/Cargo.toml
- providers/sgx/sgx-app/src/sgx_app.rs
- providers/sgx/sgx-runner/Cargo.toml
- providers/softsign/Cargo.toml
- providers/softsign/src/main.rs
update tendermint tendermint-p2p at the same time.
> Problem: upgrade to tendermint-rs 0.19 fails(#51)

- Cargo.lock
> Problem: yanked dependency (#78)

- .github/workflows/tmkms.yml
- Cargo.lock
- providers/nitro/nitro-helper/Cargo.toml
- providers/nitro/nitro-helper/src/command.rs
- providers/nitro/nitro-helper/src/key_utils.rs
use aws-rust-sdk instead of rusoto
> Problem: legacy rusoto crates are used(#66)

- providers/nitro/nitro-helper/src/key_utils.rs
get credentials from Instance Metadata Service Version 2
> Problem: IMDSv1 used to obtain the credentials information

- Cargo.lock
- Dockerfile.nitro
- providers/nitro/nitro-enclave/Cargo.toml
- providers/nitro/nitro-enclave/src/nitro.rs
- providers/nitro/nitro-helper/Cargo.toml
- providers/nitro/nitro-helper/src/command.rs
- providers/nitro/nitro-helper/src/key_utils.rs
- providers/nitro/nitro-helper/src/main.rs
- providers/nitro/nitro-helper/src/shared.rs
generate keypair in nitro enclave, and send public key and encrypted private key to host. The command is:
```
tmkms-nitro-helper init 
-a $KMS_REGION 
-p bech32 
-b crocnclconspub 
-k $KMS_ID 
--cid $(nitro-cli describe-enclaves | jq -r .[0].EnclaveCID)
```
> Problem:  Nitro initial key generation done on the host(#82)

- providers/nitro/nitro-helper/src/command.rs
- providers/nitro/nitro-helper/src/command/launch_all.rs
- providers/nitro/nitro-helper/src/main.rs
- providers/nitro/nitro-helper/src/state.rs
add a receiver to receive the signal, check the stop signal after getting data from the state sync socket.
> Problem: the process is not shutdown gracefully(#108)

- Cargo.lock
Solution: `cargo update` the respective crates
> Problem: yanked crates (fixes #148)

- .github/workflows/tmkms.yml
- Cargo.lock
Solution: temporarily forced an older nightly version until the dependencies are upgraded
> Problem: build pipelines fail

- .github/workflows/docker-publish.yml
- .github/workflows/tmkms.yml
- Dockerfile.sgx
- README.md
- integration-test/flake.lock
- integration-test/flake.nix
- integration-test/run.sh
Solution: replaced nix-shell with nix-develop
> Problem: integration test fails to run

- Cargo.lock
Solution: `cargo update -p sha2`
> Problem: a yanked dependency

- Cargo.lock
- providers/nitro/nitro-helper/Cargo.toml
👮🏻👮🏻👮🏻 !!!! REFERENCE THE PROBLEM YOUR ARE SOLVING IN THE PR TITLE AND DESCRIBE YOUR SOLUTION HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻
Thank you for your code, it's appreciated! :)
> Problem: upgrading aws-* crates to 0.12 fails

- Cargo.lock
- providers/nitro/nitro-helper/Cargo.toml
Solution: bumped the crates together
> Problem: upgrading aws-* crates to 0.15 fails (fixes #338)

- LICENSE
- providers/nitro/nitro-helper/src/command/nitro_enclave.rs
- providers/nitro/nitro-helper/src/tracing_layer.rs
- script/tmkms-nitro/verify.py
- src/chain/state.rs
- src/chain/state/error.rs
- src/config/validator.rs
- src/connection.rs
- src/error.rs
- src/rpc.rs
- src/session.rs
Solution: Update related files
> Problem: License file is not up-to-dated

- .github/workflows/tmkms.yml
- Cargo.lock
- providers/nitro/nitro-helper/Cargo.toml
Solution: bump the aws-* crates together
> Problem: upgrade of aws-* crates to 0.48 fails (fixes #415)

- .github/workflows/tmkms.yml
Solution: switch to dtolnay/rust-toolchain
> Problem: actions-rs are not actively maintained

- Cargo.lock
- providers/nitro/nitro-helper/Cargo.toml
- providers/nitro/nitro-helper/src/config.rs
- providers/nitro/nitro-helper/src/main.rs
- providers/sgx/sgx-runner/Cargo.toml
- providers/sgx/sgx-runner/src/config.rs
- providers/sgx/sgx-runner/src/main.rs
- providers/softsign/Cargo.toml
- providers/softsign/src/main.rs
- src/utils.rs
Solution: upgrade to v4
by adjusting the API-related changes in all runner/helper crates
> Problem: clap v3 is in maintainance mode

- Cargo.lock
- Cargo.toml
- providers/nitro/nitro-enclave/Cargo.toml
- providers/nitro/nitro-helper/Cargo.toml
- providers/sgx/sgx-app/Cargo.toml
- providers/sgx/sgx-runner/Cargo.toml
- providers/softsign/Cargo.toml
Solution: bump all the related crates together
> Problem: tendermint and aws upgrades fail (fixes #457)

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- providers/nitro/nitro-enclave/Cargo.toml
- providers/nitro/nitro-helper/Cargo.toml
- providers/sgx/sgx-app/Cargo.toml
- providers/sgx/sgx-runner/Cargo.toml
- providers/softsign/Cargo.toml
Solution: upgrade all crates together
> Problem: upgrade of tendermint and aws crates fails (fixes #500, fixes #501)

- providers/nitro/nitro-helper/src/tracing_layer.rs
Solution: Return from log parsing rather panicking
As discussed in the hackerone issue #1601600 - here's a patch for the panics in log parsing. Note that some of the panics had been fixed by changes made since #1601600 was created. This PR adds tests to cover all cases and fixes the remaining panics.
I hereby certify that my contribution is in accordance with the Developer Certificate of Origin (https://developercertificate.org/).
> Problem: Log parsing panics under some circumstances

- .github/workflows/tmkms.yml
Solution: added the merge group event
> Problem: CI is not executed on the merge queue
