crypto-com/tmkms-light

providers/sgx/sgx-runner/src/command.rs

Solution: add consensus-key.backup to the key_backup_data_path

Problem: (fix #54)option key_backup_data_path means differently for command init and recover in sgx provide

---

providers/sgx/sgx-runner/src/shared.rs

Solution: use the default standard character set for base64 encoding

Problem: incorrect character set for external cloud payload in SGX (fixes #102)

---

Cargo.lock
Dockerfile.nitro
NOTICE
providers/nitro/nitro-enclave/Cargo.toml
providers/nitro/nitro-enclave/src/nitro.rs
providers/nitro/nitro-helper/src/command.rs
providers/nitro/nitro-helper/src/key_utils.rs
providers/nitro/nitro-helper/src/shared.rs
script/tmkms-nitro/default.nix
script/tmkms-nitro/verify.py

Solution:
- extended response for keygen in the helper + extra comments/small refactor
- nitro enclave returns an attestation doc for the generated pubkey + used AWS KMS key id
- added a small Python verification script to illustrate how the attestation doc payload can be processed

Problem: no proof that a keypair was generated inside NE (fixes #92)

---

Dockerfile.sgx
README.md

Solution: added a Dockerfile which should have a somewhat reproducible build environment
and force the RUSTFLAGS

Problem: SGX compilation instructions may not be using HW cryptographic acceleration (fixes #67)

---

CHANGELOG.md
Cargo.lock
Cargo.toml
providers/nitro/nitro-enclave/Cargo.toml
providers/nitro/nitro-helper/Cargo.toml
providers/sgx/sgx-app/Cargo.toml
providers/sgx/sgx-runner/Cargo.toml
providers/softsign/Cargo.toml
src/rpc.rs

Solution: upgraded all crates at once, a small API fix
and updated the changelog

Problem: latest tendermint-* 0.20 not used

---

.github/workflows/tmkms.yml
Cargo.lock
Cargo.toml
providers/nitro/nitro-enclave/Cargo.toml
providers/nitro/nitro-helper/Cargo.toml
providers/sgx/sgx-app/Cargo.toml
providers/sgx/sgx-runner/Cargo.toml
providers/softsign/Cargo.toml

update to tendermint to 0.21 and use `cargo update` to update the Cargo.lock

Problem: upgrade to tendermint 0.21 fails(#137)

---

Cargo.lock

Solution: `cargo update -p crypto-bigint`

Problem: a yank crate version (fixes #173)

---

Cargo.lock
Cargo.toml
providers/nitro/nitro-enclave/Cargo.toml
providers/nitro/nitro-helper/Cargo.toml
providers/sgx/sgx-app/Cargo.toml
providers/sgx/sgx-runner/Cargo.toml
providers/softsign/Cargo.toml
src/rpc.rs

Solution: bump all tendermint-rs crates together + small struct change

Problem: upgrade to tendermint-* 0.22.0 fails (fixes #178)

---

Cargo.lock

Solution: bump thread_local crate version'
via cargo update
(transitive dependency)

Problem: RUSTSEC-2022-0006

---

providers/nitro/nitro-helper/src/key_utils.rs

I tore down the box I was seeing this problem on, apologies for that, but here is some information based on memory.
During attempts to run `init` on `main`, I was seeing a `tokio` runtime problem where the error message suggested adding `enable_time`. After adding that, it then complained about `enable_io` so I chose to use the `enable_all()` shorthand here. The backtrace was showing that the `tokio::sleep` call was originating in one of the aws dependencies.
After this, I was able to builld and use `init` as expected.

Enables io and time tokio drivers on the tokio runtime builder

---

Cargo.lock
Cargo.toml

Solution: bump tendermint-* crates and prost together
via `cargo update`

Problem: upgrading to tendermint 0.23.7 crates fails to build (fixes #316) (fixes #292)

---

.github/workflows/tmkms.yml
Cargo.lock
Dockerfile.nitro

Solution:
- bumped crates
- updated the toolchain
- updated dockerfile dependencies as per the upstream one: https://github.com/aws/aws-nitro-enclaves-acm/blob/main/env/enclave/Dockerfile

Problem: tendermint-p2p upgrade to 0.23.8 fails to build on nitro (fixes #366)

---

Cargo.lock
providers/nitro/nitro-enclave/Cargo.toml
providers/nitro/nitro-enclave/src/main.rs
providers/nitro/nitro-enclave/src/nitro.rs
providers/nitro/nitro-enclave/src/nitro/state.rs
providers/nitro/nitro-helper/Cargo.toml
providers/nitro/nitro-helper/src/command.rs
providers/nitro/nitro-helper/src/enclave_log_server.rs
providers/nitro/nitro-helper/src/key_utils.rs
providers/nitro/nitro-helper/src/proxy.rs
providers/nitro/nitro-helper/src/state.rs
providers/nitro/nitro-helper/src/tracing_layer.rs

Solution: bumped the related crates in NE together
+ adjusted the API based on the breaking changes in vsock

Problem: upgrading aws-* crates to 0.46 fails (fixes #367)

---

.devcontainer/Dockerfile
.github/workflows/tmkms.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
Dockerfile.sgx
providers/nitro/nitro-enclave/Cargo.toml
providers/nitro/nitro-enclave/src/nitro.rs
providers/nitro/nitro-helper/Cargo.toml
providers/sgx/sgx-app/Cargo.toml
providers/sgx/sgx-app/src/sgx_app.rs
providers/sgx/sgx-app/src/sgx_app/cloud.rs
providers/sgx/sgx-app/src/sgx_app/cloud/keywrap.rs
providers/sgx/sgx-app/src/sgx_app/keypair_seal.rs
providers/sgx/sgx-runner/Cargo.toml
providers/sgx/sgx-runner/src/command.rs
providers/softsign/Cargo.toml
providers/softsign/src/key_utils.rs

Solution: bumped rsa + rewrote according to API changes;
upgraded sgx-related crates + new compiler version;
removed crypto2 tests and added a custom keywrap in tests
(crypto2 didn't compile on the latest compiler / was in conflict
with other crate updates)

Problem: upgrading sha2 to 0.10.* fails to compile on sgx targets (fxes #225)

---

.github/workflows/docker-publish.yml

Solution:
bumped toolchain to 1.62.1 (same as the other CI action)
The error was:
```
package `time v0.3.11` cannot be built because it requires rustc 1.57.0 or newer, while the currently active rustc version is 1.56.1
```

Problem: docker publish job fails due to an old toolchain

---

.github/workflows/tmkms.yml
Cargo.lock
Cargo.toml

Solution: upgraded tendermint-* crates together with prost

Problem: upgrade to prost 0.11 fails (fixes #383)

---

CHANGELOG.md
Cargo.lock
Cargo.toml
providers/nitro/nitro-enclave/Cargo.toml
providers/nitro/nitro-helper/Cargo.toml
providers/sgx/sgx-app/Cargo.toml
providers/sgx/sgx-app/src/main.rs
providers/sgx/sgx-runner/Cargo.toml
providers/softsign/Cargo.toml
src/utils.rs

Solution: added handling of an extra arg due to the latest enclave runner
plus a fix for the payload reading

Problem: sgx provider doesn't work in 0.4 (fixes #386)

---

Cargo.lock
providers/nitro/nitro-helper/Cargo.toml

Solution: bumped the crates together

Problem: upgrade of aws-* crate to 0.47 fails (fixes #402)

---

Cargo.lock
Cargo.toml
providers/nitro/nitro-enclave/Cargo.toml
providers/nitro/nitro-helper/Cargo.toml
providers/sgx/sgx-app/Cargo.toml
providers/sgx/sgx-runner/Cargo.toml
providers/softsign/Cargo.toml

Solution: upgrade the related (aws- and tendermint) crates together

Problem: automated dependency upgrades failed (fixs #431, fixes #430)

---

.github/workflows/tmkms.yml

Solution: removed the unmaintained crate ignore, as it is no longer present in Cargo.lock

Problem: unnecessary ignore in CI audit scan

---

CONTRIBUTING.md

This PR fixes the typo in the documentation

Fix typo in documentation
